imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BFSiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    translator: ~

services:
    fos_user.doctrine_registry:
        alias: doctrine

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: "bestfootball"
    fragments:       ~
    http_method_override: true
#fos_user
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: BF\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
            from_email:
                address:        registration@bestfootball.fr
                sender_name:    Registration at bestfootball.fr
    resetting:
        email:
            from_email:
                address:        resetting@bestfootball.fr
                sender_name:    Resetting your Bestfootball password

#fos_oauth_server
fos_oauth_server:
    db_driver: orm
    client_class:        BF\RestApiBundle\Entity\Client
    access_token_class:  BF\RestApiBundle\Entity\AccessToken
    refresh_token_class: BF\RestApiBundle\Entity\RefreshToken
    auth_code_class:     BF\RestApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username
        options:
            supported_scopes: user

#nelmio API documentation
nelmio_api_doc: ~

#fos RestApi
# Disable the default view annotations
sensio_framework_extra:
    view:
        annotations: false

# Rest configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
    access_denied_listener:
        json: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Pulse 000 - ffmpeg bundle
#dubture_f_fmpeg:
#    ffmpeg_binary: /home/joris/bin/ffmpeg
#    ffprobe_binary: /home/joris/bin/ffprobe
#    binary_timeout: 300 # Use 0 for infinite
#    threads_count: 4

#configuration for the HWIoauth bundle
hwi_oauth:
    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            facebook: facebook_id
            google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "694354014040156"
            client_secret:       "55d4070a9dfa588b63027fe51bd7010e"
            scope:               email user_about_me user_photos user_birthday 
            infos_url: "https://graph.facebook.com/me?fields=id,name,last_name,first_name,picture.type(large),birthday,email,gender"
            paths:
                username:       id
                lastname:       last_name
                firstname:      first_name
                email:          email
                profilepicture: picture.data.url
                gender:         gender
                birthday:       birthday

        google:
            type:                google
            client_id:           "764453370712-e9v39pr3vh6q72gq9662h8vnf83ggl1q.apps.googleusercontent.com"
            client_secret:       "nHGcEYTUbK4-Rqf4HlQJ65Kb"
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
#Comur image

comur_image:
    config:
        cropped_image_dir: 'cropped'
        thumbs_dir: 'thumbnails'
        media_lib_thumb_size: 150
        web_dirname: 'uploads/img'
        translation_domain: 'ComurImageBundle'
        gallery_thumb_size: 150
        gallery_dir: 'gallery'
