bf_ambassadeur:
    resource: "@BFAmbassadeurBundle/Resources/config/routing.yml"
    prefix:   /ambassadeur

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

comur_image:
    resource: "@ComurImageBundle/Resources/config/routing.yml"
    prefix:   /

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

bf_rest_api:
    resource: "@BFRestApiBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest

bf_user:
    resource: "@BFUserBundle/Resources/config/routing.yml"
    prefix:   /
#The whole website

bf_site:
    resource: "@BFSiteBundle/Resources/config/routing.yml"
    prefix:   /

# FOSAuthServerBundle
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
