# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_AMBASSADEUR: ROLE_USER
        ROLE_ADMIN:       ROLE_AMBASSADEUR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        api:
            pattern:    ^/api/.*
            fos_oauth:  true
            stateless:  true
            anonymous:  false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider    

            logout:       true
            anonymous:    true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/view, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/ambassadeur, role: ROLE_AMBASSADEUR }
        - { path: ^/oauth/v2/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/search, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fr/home, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/home, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/upload, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/upload, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/duel, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/duel, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/myduels, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/myduels, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/myvideos, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/myvideos, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/fr/settings, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/en/settings, role: IS_AUTHENTICATED_FULLY }


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
