bf_site_homepage:
    path:     /
    defaults: { _controller: BFSiteBundle:Home:index }
    methods:  [GET]

bf_site_logged_home:
    path:     /home
    defaults: { _controller: BFSiteBundle:Logged:logged }
    methods:  [GET]

bf_site_challenges:
    path:     /challenges
    defaults: { _controller: BFSiteBundle:Home:challenges }
    methods:  [GET]

bf_site_partnerChallenges:
    path:     /partnerChallenges
    defaults: { _controller: BFSiteBundle:Home:partnerChallenges }
    methods:  [GET]

bf_site_challengeview:
    path:     /challenge/{id}
    defaults: { _controller: BFSiteBundle:Home:challengeView }
    requirements:
        id: -?\d+
    methods:  [GET]

bf_site_about:
    path:     /about
    defaults: { _controller: BFSiteBundle:Home:about }
    methods:  [GET]

bf_site_rules:
    path:     /rules
    defaults: { _controller: BFSiteBundle:Home:rules }
    methods:  [GET]

bf_site_contact:
    path:     /contact
    defaults: { _controller: BFSiteBundle:Home:contact }
    methods:  [GET,POST]

bf_site_search:
    path:     /search
    defaults: { _controller: BFSiteBundle:Logged:search }
    methods:  [POST,GET]

bf_site_partners:
    path:     /partners
    defaults: { _controller: BFSiteBundle:Information:partners }
    methods:  [GET]

bf_site_press:
    path:     /press
    defaults: { _controller: BFSiteBundle:Information:press }
    methods:  [GET]

bf_site_privacy:
    path:     /privacy
    defaults: { _controller: BFSiteBundle:Information:privacy }
    methods:  [GET]

bf_site_terms:
    path:     /terms
    defaults: { _controller: BFSiteBundle:Information:terms }
    methods:  [GET]

bf_site_conditions:
    path:     /conditions
    defaults: { _controller: BFSiteBundle:Information:conditions }
    methods:  [GET]

bf_site_community:
    path:     /comunity
    defaults: { _controller: BFSiteBundle:Information:community }
    methods:  [GET]

bf_site_prediction:
    path:     /prediction
    defaults: { _controller: BFSiteBundle:Logged:prediction }
    methods:  [GET]

bf_site_freestyle:
    path:     /freestyle
    defaults: { _controller: BFSiteBundle:Video:freestyle }
    methods:  [GET]
#this section does all the routes for the video section

bf_site_video:
    path:     /view/{id}
    defaults: { _controller: BFSiteBundle:Video:view, id: null }
    requirements:
        id: -?\d+
    methods:  [GET]

bf_site_video_report:
    path:     /video/report/{id}
    defaults: { _controller: BFSiteBundle:Video:report}
    requirements:
        id: -?\d+
    methods:  [GET,POST]

bf_site_upload:
    path:     /upload/{type}/{id}
    defaults: { _controller: BFSiteBundle:Video:upload }
    requirements:
        id: -?\d+
    methods:  [GET,POST]

bf_site_video_delete:
    path:     /deletevideo/{id}
    defaults: { _controller: BFSiteBundle:Video:delete }
    requirements:
        id: -?\d+
    methods:  [GET,POST]

bf_site_video_modify:
    path:     /modifyvideo/{id}
    defaults: { _controller: BFSiteBundle:Video:modify }
    requirements:
        id: -?\d+
    methods:  [GET,POST]

bf_site_video_twitter:
    path:     /video/twitter/{id}
    defaults: { _controller: BFSiteBundle:Video:twitter }
    requirements:
        id: -?\d+
    methods:  [GET,POST]
#this section does all the routes for the profile section

bf_site_profile:
    path:     /profile/{username}
    defaults: { _controller: BFSiteBundle:Profile:view }
    methods:  [GET]

bf_site_profile_followers:
    path:     /profile/{username}/followers
    defaults: { _controller: BFSiteBundle:Follow:followersUser }
    methods:  [GET]

bf_site_videos:
    path:     /myvideos
    defaults: { _controller: BFSiteBundle:Profile:videos }
    methods:  [GET]

bf_site_profile_duels:
    path:     /myduels
    defaults: { _controller: BFSiteBundle:Duel:myduels }
    methods:  [GET]

bf_site_settings:
    path:     /settings
    defaults: { _controller: BFSiteBundle:Profile:settings }
    methods:  [GET,POST]

bf_site_settings_info:
    path:     /settings/info
    defaults: { _controller: BFSiteBundle:Profile:settingsInfo }
    methods:  [PUT,POST]

bf_site_settings_picture:
    path:     /settings/picture
    defaults: { _controller: BFSiteBundle:Profile:settingsPicture }
    methods:  [PUT,POST]

bf_site_settings_reset_password:
    path:     /settings/password
    defaults: { _controller: BFSiteBundle:Profile:changePassword }
    methods:  [PUT,POST]

bf_site_settings_reset_username:
    path:     /settings/username
    defaults: { _controller: BFSiteBundle:Profile:changeUsername }
    methods:  [PUT,POST]

#this section does all the routes for the admin section
bf_site_admin:
    path:     /admin
    defaults: { _controller: BFSiteBundle:Admin:index }
    methods:  [GET]

bf_site_admin_challenges:
    path:     /admin/challenges
    defaults: { _controller: BFSiteBundle:Admin:challenges }
    methods:  [GET]

bf_site_admin_addChallenge:
    path:     /admin/addchallenge
    defaults: { _controller: BFSiteBundle:Admin:addChallenge }
    methods:  [GET,POST]

bf_site_admin_modchallenge:
    path:     /admin/challenges/mod/{id}
    defaults: { _controller: BFSiteBundle:Admin:modChallenge }
    methods:  [GET,POST]

bf_site_admin_delchallenge:
    path:     /admin/challenges/del/{id}
    defaults: { _controller: BFSiteBundle:Admin:delChallenge }
    methods:  [GET,POST]

bf_site_admin_users:
    path:     /admin/users
    defaults: { _controller: BFSiteBundle:Admin:users }
    methods:  [GET]

bf_site_admin_reports:
    path:     /admin/reports
    defaults: { _controller: BFSiteBundle:Admin:reports }
    methods:  [GET]

bf_site_admin_delvideo:
    path:     /admin/reports/delvideo/{id}
    defaults: { _controller: BFSiteBundle:Admin:deleteVideo }
    methods:  [POST,GET]

bf_site_admin_okvideo:
    path:     /admin/reports/okvideo/{id}
    defaults: { _controller: BFSiteBundle:Admin:okVideo }
    methods:  [POST,GET]




#this section does all the routes for the duel section

bf_site_duel_create:
    path:     /duel/create/{username}
    defaults: { _controller: BFSiteBundle:Duel:create }
    methods:  [GET,POST]

bf_site_duel_accept:
    path:     /duel/accept/{id}
    defaults: { _controller: BFSiteBundle:Duel:accept }
    methods:  [POST,GET]

bf_site_duel_decline:
    path:     /duel/decline/{id}
    defaults: { _controller: BFSiteBundle:Duel:decline }
    methods:  [POST,GET]


bf_site_duel_view:
    path:     /duel/view/{id}
    defaults: { _controller: BFSiteBundle:Duel:view }
    methods:  [GET]

#the routes for the following code

bf_site_follow:
    path:     /follow/
    defaults: { _controller: BFSiteBundle:Follow:followUser }
    methods:  [POST]

bf_site_unfollow:
    path:     /unfollow/
    defaults: { _controller: BFSiteBundle:Follow:unfollowUser }
    methods:  [POST]

#the routes for the ranking pages
bf_site_ranking_challenge:
    path:     /ranking/challenge/{country}/{state}
    defaults: { _controller: BFSiteBundle:Ranking:challenge }
    requirements:
        country: France|United States|Belgium|global
    methods:  [GET]

bf_site_ranking_duel:
    path:     /ranking/duel/{country}/{state}
    defaults: { _controller: BFSiteBundle:Ranking:duel }
    requirements:
        country: France|United States|Belgium|global
    methods:  [GET]

#the routes for the AJAX calls.

bf_site_api_userinfo:
    path: /home/userinfo
    defaults: { _controller: BFSiteBundle:Ajax:userInfo }
    methods:  [GET]

bf_site_api_challenge:
    path: /home/challenge
    defaults: { _controller: BFSiteBundle:Ajax:getChallenge }
    methods:  [GET,POST]

bf_site_api_notifread:
    path: /home/notificationread
    defaults: { _controller: BFSiteBundle:Ajax:notifread }
    methods:  [POST]

bf_site_api_checkusername:
    path: /home/checkusername
    defaults: { _controller: BFSiteBundle:Ajax:checkUsername }
    methods:  [POST]

bf_site_api_duelUseVideo:
    path: /home/duelUseVideo
    defaults: { _controller: BFSiteBundle:Ajax:duelCopyVideo }
    methods:  [POST]

bf_site_api_predict:
    path: /home/predictUser
    defaults: { _controller: BFSiteBundle:Ajax:predict }
    methods:  [POST]

bf_site_api_comment_add:
    path: /home/comment/add
    defaults: { _controller: BFSiteBundle:Comment:create }
    methods:  [POST]

bf_site_api_comment_del:
    path: /home/comment/del
    defaults: { _controller: BFSiteBundle:Comment:delete }
    methods:  [POST]
