bf_site_homepage:
    path:     /
    defaults: { _controller: BFSiteBundle:Home:index }

bf_site_logged_home:
    path:     /home
    defaults: { _controller: BFSiteBundle:Logged:logged }

bf_site_challenges:
    path:     /challenges
    defaults: { _controller: BFSiteBundle:Home:challenges }

bf_site_partnerChallenges:
    path:     /partnerChallenges
    defaults: { _controller: BFSiteBundle:Home:partnerChallenges }

bf_site_challengeview:
    path:     /challenge/{id}
    defaults: { _controller: BFSiteBundle:Home:challengeView }
    requirements:
        id: -?\d+

bf_site_ranking:
    path:     /ranking/{country}/{state}
    defaults: { _controller: BFSiteBundle:Home:ranking }
    requirements:
        country: France|United States|Belgium|global

bf_site_about:
    path:     /about
    defaults: { _controller: BFSiteBundle:Home:about }

bf_site_rules:
    path:     /rules
    defaults: { _controller: BFSiteBundle:Home:rules }

bf_site_contact:
    path:     /contact
    defaults: { _controller: BFSiteBundle:Home:contact }

bf_site_search:
    path:     /search
    defaults: { _controller: BFSiteBundle:Logged:search }

#this section does all the routes for the video section

bf_site_video:
    path:     /view/{id}
    defaults: { _controller: BFSiteBundle:Video:view, id: null }
    requirements:
        id: -?\d+

bf_site_video_report:
    path:     /video/report/{id}
    defaults: { _controller: BFSiteBundle:Video:report}
    requirements:
        id: -?\d+

bf_site_upload:
    path:     /upload/{type}/{id}
    defaults: { _controller: BFSiteBundle:Video:upload }
    requirements:
        id: -?\d+

bf_site_video_delete:
    path:     /deletevideo/{id}
    defaults: { _controller: BFSiteBundle:Video:delete }
    requirements:
        id: -?\d+

bf_site_video_modify:
    path:     /modifyvideo/{id}
    defaults: { _controller: BFSiteBundle:Video:modify }
    requirements:
        id: -?\d+
#this section does all the routes for the profile section

bf_site_profile:
    path:     /profile/{username}
    defaults: { _controller: BFSiteBundle:Profile:view }

bf_site_videos:
    path:     /myvideos
    defaults: { _controller: BFSiteBundle:Profile:videos }

bf_site_profile_duels:
    path:     /myduels
    defaults: { _controller: BFSiteBundle:Duel:myduels }

bf_site_settings:
    path:     /settings
    defaults: { _controller: BFSiteBundle:Profile:settings }

bf_site_settings_info:
    path:     /settings/info
    defaults: { _controller: BFSiteBundle:Profile:settingsInfo }

bf_site_settings_picture:
    path:     /settings/picture
    defaults: { _controller: BFSiteBundle:Profile:settingsPicture }

#this section does all the routes for the admin section
bf_site_admin:
    path:     /admin
    defaults: { _controller: BFSiteBundle:Admin:index }

bf_site_admin_challenges:
    path:     /admin/challenges
    defaults: { _controller: BFSiteBundle:Admin:challenges }

bf_site_admin_addChallenge:
    path:     /admin/addchallenge
    defaults: { _controller: BFSiteBundle:Admin:addChallenge }

bf_site_admin_users:
    path:     /admin/users
    defaults: { _controller: BFSiteBundle:Admin:users }

bf_site_admin_reports:
    path:     /admin/reports
    defaults: { _controller: BFSiteBundle:Admin:reports }

bf_site_admin_delvideo:
    path:     /admin/reports/delvideo/{id}
    defaults: { _controller: BFSiteBundle:Admin:deleteVideo }

bf_site_admin_okvideo:
    path:     /admin/reports/okvideo/{id}
    defaults: { _controller: BFSiteBundle:Admin:okVideo }




#this section does all the routes for the duel section

bf_site_duel_create:
    path:     /duel/create/{username}
    defaults: { _controller: BFSiteBundle:Duel:create }

bf_site_duel_accept:
    path:     /duel/accept/{id}
    defaults: { _controller: BFSiteBundle:Duel:accept }

bf_site_duel_decline:
    path:     /duel/decline/{id}
    defaults: { _controller: BFSiteBundle:Duel:decline }


bf_site_duel_view:
    path:     /duel/view/{id}
    defaults: { _controller: BFSiteBundle:Duel:view }

#the routes for the following code

bf_site_follow:
    path:     /follow/
    defaults: { _controller: BFSiteBundle:Follow:followUser }

bf_site_unfollow:
    path:     /unfollow/
    defaults: { _controller: BFSiteBundle:Follow:unfollowUser }
