bf_site_homepage:
    path:     /{_locale}
    defaults: { _controller: BFSiteBundle:Home:index, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_logged_home:
    path:     /{_locale}/home
    defaults: { _controller: BFSiteBundle:Logged:logged, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_challenges:
    path:     /{_locale}/challenges
    defaults: { _controller: BFSiteBundle:Home:challenges, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_partnerChallenges:
    path:     /{_locale}/partnerChallenges
    defaults: { _controller: BFSiteBundle:Home:partnerChallenges, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_challengeview:
    path:     /{_locale}/challenge/{slug}
    defaults: { _controller: BFSiteBundle:Home:challengeView, _locale: en }
    requirements:
        id: -?\d+
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_about:
    path:     /{_locale}/about
    defaults: { _controller: BFSiteBundle:Home:about, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_rules:
    path:     /{_locale}/rules
    defaults: { _controller: BFSiteBundle:Home:rules, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_contact:
    path:     /{_locale}/contact
    defaults: { _controller: BFSiteBundle:Home:contact, _locale: en }
    methods:  [GET,POST]
    requirements:
        _locale: en|fr

bf_site_search:
    path:     /{_locale}/search
    defaults: { _controller: BFSiteBundle:Logged:search, _locale: en }
    methods:  [POST,GET]
    requirements:
        _locale: en|fr

bf_site_partners:
    path:     /{_locale}/partners
    defaults: { _controller: BFSiteBundle:Information:partners, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_press:
    path:     /{_locale}/press
    defaults: { _controller: BFSiteBundle:Information:press, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_privacy:
    path:     /{_locale}/privacy
    defaults: { _controller: BFSiteBundle:Information:privacy, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_terms:
    path:     /{_locale}/terms
    defaults: { _controller: BFSiteBundle:Information:terms, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_conditions:
    path:     /{_locale}/conditions
    defaults: { _controller: BFSiteBundle:Information:conditions, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_community:
    path:     /{_locale}/comunity
    defaults: { _controller: BFSiteBundle:Information:community, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_prediction:
    path:     /{_locale}/prediction
    defaults: { _controller: BFSiteBundle:Logged:prediction, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_freestyle:
    path:     /{_locale}/freestyle
    defaults: { _controller: BFSiteBundle:Video:freestyle, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr
#this section does all the routes for the video section

bf_site_video:
    path:     /{_locale}/view/{code}
    defaults: { _controller: BFSiteBundle:Video:view, id: null, _locale: en }
    requirements:
        id: -?\d+
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_video_report:
    path:     /{_locale}/video/report/{id}
    defaults: { _controller: BFSiteBundle:Video:report, _locale: en }
    requirements:
        id: -?\d+
    methods:  [GET,POST]
    requirements:
        _locale: en|fr

bf_site_upload:
    path:     /{_locale}/upload/{type}/{id}
    defaults: { _controller: BFSiteBundle:Video:upload, _locale: en }
    requirements:
        id: -?\d+
    methods:  [GET,POST]
    requirements:
        _locale: en|fr

bf_site_video_delete:
    path:     /{_locale}/deletevideo/{id}
    defaults: { _controller: BFSiteBundle:Video:delete, _locale: en }
    requirements:
        id: -?\d+
    methods:  [GET,POST]
    requirements:
        _locale: en|fr

bf_site_video_modify:
    path:     /{_locale}/modifyvideo/{id}
    defaults: { _controller: BFSiteBundle:Video:modify, _locale: en }
    requirements:
        id: -?\d+
    methods:  [GET,POST]
    requirements:
        _locale: en|fr

bf_site_video_twitter:
    path:     /video/twitter/{id}
    defaults: { _controller: BFSiteBundle:Video:twitter }
    requirements:
        id: -?\d+
    methods:  [GET,POST]
    requirements:
        _locale: en|fr
#this section does all the routes for the profile section

bf_site_profile:
    path:     /{_locale}/profile/{username}
    defaults: { _controller: BFSiteBundle:Profile:view, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_profile_followers:
    path:     /{_locale}/profile/{username}/followers
    defaults: { _controller: BFSiteBundle:Follow:followersUser, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_videos:
    path:     /{_locale}/myvideos
    defaults: { _controller: BFSiteBundle:Profile:videos, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_profile_duels:
    path:     /{_locale}/myduels
    defaults: { _controller: BFSiteBundle:Duel:myduels, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_settings:
    path:     /{_locale}/settings
    defaults: { _controller: BFSiteBundle:Profile:settings, _locale: en }
    methods:  [GET,POST]
    requirements:
        _locale: en|fr

bf_site_settings_info:
    path:     /{_locale}/settings/info
    defaults: { _controller: BFSiteBundle:Profile:settingsInfo, _locale: en }
    methods:  [PUT,POST]
    requirements:
        _locale: en|fr

bf_site_settings_picture:
    path:     /{_locale}/settings/picture
    defaults: { _controller: BFSiteBundle:Profile:settingsPicture, _locale: en }
    methods:  [PUT,POST]
    requirements:
        _locale: en|fr

bf_site_settings_reset_password:
    path:     /{_locale}/settings/password
    defaults: { _controller: BFSiteBundle:Profile:changePassword, _locale: en }
    methods:  [PUT,POST]
    requirements:
        _locale: en|fr

bf_site_settings_reset_username:
    path:     /{_locale}/settings/username
    defaults: { _controller: BFSiteBundle:Profile:changeUsername, _locale: en }
    methods:  [PUT,POST]
    requirements:
        _locale: en|fr

#this section does all the routes for the admin section
bf_site_admin:
    path:     /admin
    defaults: { _controller: BFSiteBundle:Admin:index }
    methods:  [GET]

bf_site_admin_challenges:
    path:     /admin/challenges
    defaults: { _controller: BFSiteBundle:Admin:challenges }
    methods:  [GET]

bf_site_admin_addChallenge:
    path:     /admin/addchallenge
    defaults: { _controller: BFSiteBundle:Admin:addChallenge }
    methods:  [GET,POST]

bf_site_admin_modchallenge:
    path:     /admin/challenges/mod/{id}
    defaults: { _controller: BFSiteBundle:Admin:modChallenge }
    methods:  [GET,POST]

bf_site_admin_delchallenge:
    path:     /admin/challenges/del/{id}
    defaults: { _controller: BFSiteBundle:Admin:delChallenge }
    methods:  [GET,POST]

bf_site_admin_users:
    path:     /admin/users
    defaults: { _controller: BFSiteBundle:Admin:users }
    methods:  [GET]

bf_site_admin_reports:
    path:     /admin/reports
    defaults: { _controller: BFSiteBundle:Admin:reports }
    methods:  [GET]

bf_site_admin_delvideo:
    path:     /admin/reports/delvideo/{id}
    defaults: { _controller: BFSiteBundle:Admin:deleteVideo }
    methods:  [POST,GET]

bf_site_admin_okvideo:
    path:     /admin/reports/okvideo/{id}
    defaults: { _controller: BFSiteBundle:Admin:okVideo }
    methods:  [POST,GET]




#this section does all the routes for the duel section

bf_site_duel_create:
    path:     /{_locale}/duel/create/{username}
    defaults: { _controller: BFSiteBundle:Duel:create, _locale: en }
    methods:  [GET,POST]
    requirements:
        _locale: en|fr

bf_site_duel_accept:
    path:     /{_locale}/duel/accept/{id}
    defaults: { _controller: BFSiteBundle:Duel:accept, _locale: en }
    methods:  [POST,GET]
    requirements:
        _locale: en|fr

bf_site_duel_decline:
    path:     /{_locale}/duel/decline/{id}
    defaults: { _controller: BFSiteBundle:Duel:decline, _locale: en }
    methods:  [POST,GET]
    requirements:
        _locale: en|fr


bf_site_duel_view:
    path:     /{_locale}/duel/view/{code}
    defaults: { _controller: BFSiteBundle:Duel:view, _locale: en }
    methods:  [GET]
    requirements:
        _locale: en|fr

#the routes for the following code

bf_site_follow:
    path:     /follow/
    defaults: { _controller: BFSiteBundle:Follow:followUser }
    methods:  [POST]

bf_site_unfollow:
    path:     /unfollow/
    defaults: { _controller: BFSiteBundle:Follow:unfollowUser }
    methods:  [POST]

#the routes for the ranking pages
bf_site_ranking_challenge:
    path:     /{_locale}/ranking/challenge/{country}/{state}
    defaults: { _controller: BFSiteBundle:Ranking:challenge, _locale: en }
    requirements:
        country: France|United States|Belgium|global
    methods:  [GET]
    requirements:
        _locale: en|fr

bf_site_ranking_duel:
    path:     /{_locale}/ranking/duel/{country}/{state}
    defaults: { _controller: BFSiteBundle:Ranking:duel, _locale: en }
    requirements:
        country: France|United States|Belgium|global
    methods:  [GET]
    requirements:
        _locale: en|fr

#the routes for the AJAX calls.

bf_site_api_userinfo:
    path: /home/userinfo
    defaults: { _controller: BFSiteBundle:Ajax:userInfo }
    methods:  [GET]

bf_site_api_challenge:
    path: /home/challenge
    defaults: { _controller: BFSiteBundle:Ajax:getChallenge }
    methods:  [GET,POST]

bf_site_api_notifread:
    path: /home/notificationread
    defaults: { _controller: BFSiteBundle:Ajax:notifread }
    methods:  [POST]

bf_site_api_checkusername:
    path: /home/checkusername
    defaults: { _controller: BFSiteBundle:Ajax:checkUsername }
    methods:  [POST]

bf_site_api_duelUseVideo:
    path: /home/duelUseVideo
    defaults: { _controller: BFSiteBundle:Ajax:duelCopyVideo }
    methods:  [POST]

bf_site_api_predict:
    path: /home/predictUser
    defaults: { _controller: BFSiteBundle:Ajax:predict }
    methods:  [POST]

bf_site_api_comment_add:
    path: /home/comment/add
    defaults: { _controller: BFSiteBundle:Comment:create }
    methods:  [POST]

bf_site_api_comment_del:
    path: /home/comment/del
    defaults: { _controller: BFSiteBundle:Comment:delete }
    methods:  [POST]

bf_site_api_language:
    path: /home/language/change/{language}
    defaults: { _controller: BFSiteBundle:Ajax:setLocale }
    methods:  [POST, GET]
