services:
    bf_site.rankinfo:
        class: BF\SiteBundle\Userinfo\BFUserinfo
        arguments: [@doctrine.orm.entity_manager]

    bf_site.randomvideos:
        class: BF\SiteBundle\Randomvideos\BFRandomvideos
        arguments: [@doctrine.orm.entity_manager]

    bf_site.videospoints:
        class: BF\SiteBundle\VideosPoints\BFVideosPoints
        arguments: [@doctrine.orm.entity_manager]

    em:
        alias: doctrine.orm.entity_manager

    bf_site.notification:
        class: BF\SiteBundle\Notification\BFNotification

    bf_site.locale_listener:
        class: BF\SiteBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber, priority: 10 }
